name: CD - Deploy Backend Services to AKS

on:
  workflow_dispatch:
  push:
    branches: [ main ]                 # IMPROVEMENT: Auto-deploy on push to main

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v1
        with: { creds: ${{ secrets.AZURE_CREDENTIALS }} }
      - run: az aks get-credentials --resource-group ${{ secrets.AKS_RG }} --name ${{ secrets.AKS_CLUSTER }} --overwrite-existing
        # IMPROVEMENT: No hard-coded cluster name, use secrets instead.
      - run: |
          kubectl apply -f k8s/configmaps.yaml
          kubectl apply -f k8s/secrets.yaml
          kubectl apply -f k8s/product-db.yaml
          kubectl apply -f k8s/order-db.yaml
          kubectl apply -f k8s/product-service.yaml
          kubectl apply -f k8s/order-service.yaml
        # IMPROVEMENT: Directly linked to latest main push builds.
      - run: az logout
