name: CD - Deploy Frontend to AKS

on:
  workflow_dispatch:
  push:
    branches: [ main ]                  # IMPROVEMENT: Auto-deploy frontend on main builds

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v1
        with: { creds: ${{ secrets.AZURE_CREDENTIALS }} }
      - run: az acr login --name ${{ secrets.ACR_NAME }}
      - name: Build & Push Frontend Image
        run: |
          docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/frontend:${{ github.sha }}-${{ github.run_id }} ./frontend/
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/frontend:${{ github.sha }}-${{ github.run_id }}
          docker tag  ${{ secrets.AZURE_CONTAINER_REGISTRY }}/frontend:${{ github.sha }}-${{ github.run_id }} ${{ secrets.AZURE_CONTAINER_REGISTRY }}/frontend:latest
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/frontend:latest
        # IMPROVEMENT: Adds proper tagging and removes reliance on manual IP injection.
      - uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RG }}
          cluster-name: ${{ secrets.AKS_CLUSTER }}
      - run: kubectl apply -f k8s/frontend.yaml
      - run: az logout
