name: Frontend CI - Build & Push Image

on:
  pull_request:
    branches: [ dev ]                   # IMPROVEMENT: PR validation
    paths: [ 'frontend/**', 'k8s/**', '.github/workflows/frontend_ci.yml' ]
  push:
    branches: [ main ]                  # IMPROVEMENT: Release builds
    paths: [ 'frontend/**', 'k8s/**', '.github/workflows/frontend_ci.yml' ]
  workflow_dispatch:

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v1
        with: { creds: ${{ secrets.AZURE_CREDENTIALS }} }
      - run: az acr login --name ${{ env.ACR_NAME }}
      - name: Build & Push Frontend Image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }} ./frontend/
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}
          docker tag  ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }} ${{ env.ACR_LOGIN_SERVER }}/frontend:latest
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:latest
      - run: az logout
